/**
 * Generates lib/email-theme.generated.ts from the :root block of
 * app/globals.css.
 *
 * Email clients parse neither oklch() nor var(), and React Email's <Tailwind>
 * takes a v3-style JS config object rather than v4's CSS-first @theme — so the
 * design tokens have to reach an email as literal hex in an object. Generating
 * that keeps one source of truth, the same trade lib/server/db/schemas/auth.ts
 * already makes.
 *
 * Light tokens only. An email carries no theme toggle, and Gmail applies its own
 * dark-mode inversion regardless, so the .dark block is not read.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const SOURCE = join(process.cwd(), 'app/globals.css')
const OUTPUT = join(process.cwd(), 'lib/email-theme.generated.ts')

// The browser resolves rem against the root font size; an email has no such
// context, and several clients drop rem outright. 16px is the browser default
// and the number Tailwind's own pixelBasedPreset assumes.
const ROOT_FONT_SIZE_PX = 16

/**
 * OKLCH to sRGB hex, via OKLab and the LMS matrices from Björn Ottosson's
 * reference implementation.
 *
 * Out-of-gamut channels are clamped per channel. The current palette sits well
 * inside sRGB, so this is a guard rather than a routine path — but a token
 * edited to a vivid colour must still produce a valid hex string rather than
 * "NaN".
 */
function oklchToHex(lightness: number, chroma: number, hueDegrees: number): string {
  const hue = (hueDegrees * Math.PI) / 180
  const a = chroma * Math.cos(hue)
  const b = chroma * Math.sin(hue)

  const longCubeRoot = lightness + 0.3963377774 * a + 0.2158037573 * b
  const mediumCubeRoot = lightness - 0.1055613458 * a - 0.0638541728 * b
  const shortCubeRoot = lightness - 0.0894841775 * a - 1.291485548 * b

  const long = longCubeRoot ** 3
  const medium = mediumCubeRoot ** 3
  const short = shortCubeRoot ** 3

  const linear = [
    4.0767416621 * long - 3.3077115913 * medium + 0.2309699292 * short,
    -1.2684380046 * long + 2.6097574011 * medium - 0.3413193965 * short,
    -0.0041960863 * long - 0.7034186147 * medium + 1.707614701 * short,
  ]

  const channels = linear.map((channel) => {
    const encoded =
      channel <= 0.0031308
        ? 12.92 * channel
        : 1.055 * Math.pow(channel, 1 / 2.4) - 0.055
    const clamped = Math.min(1, Math.max(0, encoded))
    return Math.round(clamped * 255)
      .toString(16)
      .padStart(2, '0')
  })

  return `#${channels.join('')}`
}

function readRootBlock(css: string): string {
  // The first :root block is the light palette; .dark follows it and is not
  // read. [^}]* stops at the first closing brace, and neither block nests.
  const match = css.match(/:root\s*\{([^}]*)\}/)
  if (!match) {
    throw new Error(`No :root block found in ${SOURCE}`)
  }
  return match[1]
}

function parseColors(block: string): Record<string, string> {
  const colors: Record<string, string> = {}
  const token = /--([a-z0-9-]+):\s*oklch\(([^)]+)\)/g

  for (const [, name, value] of block.matchAll(token)) {
    if (value.includes('/')) {
      // A translucent token cannot become a 6-digit hex, and silently dropping
      // the alpha would ship a colour nobody chose.
      throw new Error(
        `--${name} uses alpha (oklch(${value})), which an email palette cannot express`,
      )
    }

    const parts = value.trim().split(/\s+/).map(Number)
    if (parts.length !== 3 || parts.some(Number.isNaN)) {
      throw new Error(`--${name}: cannot parse oklch(${value})`)
    }

    colors[name] = oklchToHex(parts[0], parts[1], parts[2])
  }

  if (Object.keys(colors).length === 0) {
    throw new Error('The :root block contained no oklch tokens')
  }

  return colors
}

function parseRadius(block: string): string {
  const match = block.match(/--radius:\s*([\d.]+)rem/)
  if (!match) {
    throw new Error('No --radius found in the :root block')
  }
  return `${Math.round(Number(match[1]) * ROOT_FONT_SIZE_PX)}px`
}

function main(): void {
  // A cheap proof the colour maths is wired up correctly: pure white and pure
  // black are exact in every colour space, so a wrong matrix cannot pass this.
  if (oklchToHex(1, 0, 0) !== '#ffffff' || oklchToHex(0, 0, 0) !== '#000000') {
    throw new Error('oklchToHex self-check failed')
  }

  const block = readRootBlock(readFileSync(SOURCE, 'utf8'))
  const colors = parseColors(block)
  const radius = parseRadius(block)

  const entries = Object.entries(colors)
    .map(([name, hex]) => `    '${name}': '${hex}',`)
    .join('\n')

  const file = `// GENERATED by \`npm run schema:email-theme\` — do not edit.
// Source: app/globals.css (:root, light tokens only).

export const emailTheme: { colors: Record<string, string>; radius: string } = {
  colors: {
${entries}
  },
  radius: '${radius}',
}
`

  writeFileSync(OUTPUT, file)
  console.log(
    `[email-theme] wrote ${OUTPUT} — ${Object.keys(colors).length} colors, radius ${radius}`,
  )
}

main()
